Pagination
Greed2kk/gs_rnd pull request #12
Opened 2019-09-06 15:45 UTC by Greed2kk

2019-09-09 06:23 UTC, tmcgroul requested changes

2019-09-09 06:23 UTC, tmcgroul commented on gs_rnd/client/static/views/marker_li.js
> +        console.log(this.maxPages);
зочем

2019-09-09 06:23 UTC, tmcgroul commented on gs_rnd/client/static/views/marker_li.js
> +        this.offset += this.limit;
а теперь перенеси `offset` и `top` в backbone модель и делай `this.pagination.reset` в обработчике события на изменение `top` или `offset`

2019-09-09 06:23 UTC, tmcgroul commented on gs_rnd/client/static/views/marker_li.js
> +                // collection: this.getOption('collection'),
удалить

2019-09-09 06:23 UTC, tmcgroul commented on gs_rnd/client/static/views/marker_li.js
> +
проверяй код перед пушем

2019-09-09 07:08 UTC, Greed2kk commented on gs_rnd/client/static/views/marker_li.js
> +
хорошо

2019-09-09 07:10 UTC, Greed2kk commented on gs_rnd/client/static/views/marker_li.js
> +                // collection: this.getOption('collection'),
хорошо

2019-09-09 07:11 UTC, Greed2kk commented on gs_rnd/client/static/views/marker_li.js
> +        console.log(this.maxPages);
хотелосЪ глянуть шо там
Это я в пятницу еще писал, думал дома подправить, но чет не подправил...(

2019-09-09 07:11 UTC, Greed2kk commented on gs_rnd/client/static/views/marker_li.js
> +        console.log(this.maxPages);
атдихал

2019-09-11 09:38 UTC, tmcgroul requested changes

2019-09-11 09:38 UTC, tmcgroul commented on gs_rnd/client/static/views/marker_li.js
> +import * as _ from "underscore";
`import * as _ from "underscore";`
лучше писать:
`import _ from "underscore";`

2019-09-11 09:38 UTC, tmcgroul commented on gs_rnd/client/static/views/marker_li.js
> +            limiter: {
переделай на такую структуру:
```js
limiters: [
    {
        value: 2,
        selected: true
    }
    ...
]
```

2019-09-11 15:08 UTC, Greed2kk commented on gs_rnd/client/static/views/marker_li.js
> +            limiter: {
уууу, сложна(((

2019-09-23 14:37 UTC, tmcgroul approved these changes

2019-09-23 14:38 UTC, merged